### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by urmaul** [giovanniberti/robusta#3]
Hello. I depend on functionality of returning JniResult it the java->rust calls and because of that I have to depend on the git branch. Could you please make a release so I can depend on a version instead?

**Comment by giovanniberti** [comment]
Hi @urmaul! Glad to see the project is used by other people :). Are you having any other issues with the latest git release? Unfortunately I haven't been able to progress with development lately (as you can see from the latest commit date), that's why I decided to postpone release until having tested the code more thoroughly.

How long have you been using the crate from git? If everything works for you I might consider releasing a new release anyway.

**Comment by urmaul** [comment]
About a week, I guess. Everything worked fine so far.

My use case is not tricky though. It's an empty class with a single function with one string argument and `JniResult<String>` as an output, no state is preserved between the calls.

**Comment by giovanniberti** [comment]
See c453536
